CREATE TABLE IF NOT EXISTS events (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"date"	TEXT NOT NULL,
	"description"	TEXT NOT NULL,
	"ownerId"	INTEGER NOT NULL,
	"groupId"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
)